// Code generated by "stringer -type Color"; DO NOT EDIT.

package internal

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ColRed-0]
	_ = x[ColGreen-1]
	_ = x[ColBlue-2]
}

const _Color_name = "ColRedColGreenColBlue"

var _Color_index = [...]uint8{0, 6, 14, 21}

func (i Color) String() string {
	if i < 0 || i >= Color(len(_Color_index)-1) {
		return "Color(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Color_name[_Color_index[i]:_Color_index[i+1]]
}
